### ISSUE TITLE
'finish' is emitted before all the data has been flushed

### ISSUE THREAD

**Issue by hmalphettes** [hmalphettes/elasticsearch-streams#1]
When consuming a read-stream that is faster than Elasticsearch we end-up in situation where the ES write stream's end method is called although not all data has been written yet.

This is because our naive overriding of the write stream's end method assumes that all data has been written... I am not sure where I misinterpreted the documentation to that regard and concldued I was safe overriding it.

The best practice consists having the write stream listen to itself for the `finish` event, then flush and emit another event: `close`.
Reference: https://github.com/joyent/node/issues/5315#issuecomment-16670354

The drawback is that one who uses the write stream must now listen to the non-documented `close` event instead of listening to the documented `finish` event.

Someone noted that implementing a transform stream will get the required flushing behavior for free and avoid the `close` event all together.

**Comment by TomFrost** [comment]
Not to raise the dead, but I just ran into this same problem with this library; I'm using a pluggable streaming framework that requires `finish` to literally mean `finish`, and using `close` instead breaks that.

If I may humbly suggest my own solution to this problem, it's become a fairly popular workaround to this shortcoming: https://github.com/TomFrost/FlushWritable

Extend that instead of the standard Writable, rename _flushBulk to _flush, and now your `finish` event will literally mean that writing has been complete. For the sake of backward compatibility and completeness, `close` could be retained to fire off either simultaneously or when all the connections have been closed.

**Comment by hmalphettes** [comment]
Hi @TomFrost sorry for the delay. Thanks for the suggestion and the link to FlushWritable.
Nice way to deal with this situation. Looks even nicer than flush-write-stream. If you have fixed this somewhere and want to make a PR I am happy to merge it.
